version: "2"
run:
  tests: false
linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - misspell
    - nakedret
    - nilnil
    - prealloc
    - unconvert
    - unparam
  settings:
    gocritic:
      disabled-checks:
        - whyNoLint
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
    gocyclo:
      min-complexity: 15
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: retroarch/
        linters:
          - goconst
      - path: assets/service.go
        linters:
          - goconst
      - path: library/library.go
        linters:
          - goconst
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
