version: "2"
run:
  tests: false
linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - misspell
    - nakedret
    - nilnil
    - prealloc
    - unconvert
    - unparam
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
    gocyclo:
      min-complexity: 15
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
