// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function DeleteRom(arg1:number):Promise<void>;

export function DeleteSave(arg1:number,arg2:string,arg3:string):Promise<void>;

export function DeleteState(arg1:number,arg2:string,arg3:string):Promise<void>;

export function DownloadRom(arg1:number):Promise<string>;

export function DownloadRomToLibrary(arg1:number):Promise<void>;

export function DownloadServerSave(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DownloadServerState(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetConfig():Promise<types.AppConfig>;

export function GetCover(arg1:number,arg2:string):Promise<string>;

export function GetLibrary():Promise<Array<types.Game>>;

export function GetPlatformCover(arg1:number,arg2:string):Promise<string>;

export function GetPlatforms():Promise<Array<types.Platform>>;

export function GetRom(arg1:number):Promise<types.Game>;

export function GetRomDownloadStatus(arg1:number):Promise<boolean>;

export function GetSaves(arg1:number):Promise<Array<types.FileItem>>;

export function GetServerSaves(arg1:number):Promise<Array<types.ServerSave>>;

export function GetServerStates(arg1:number):Promise<Array<types.ServerState>>;

export function GetStates(arg1:number):Promise<Array<types.FileItem>>;

export function Greet(arg1:string):Promise<string>;

export function Login():Promise<string>;

export function PlayRom(arg1:number):Promise<void>;

export function Quit():Promise<void>;

export function SaveConfig(arg1:types.AppConfig):Promise<string>;

export function SelectLibraryPath():Promise<string>;

export function SelectRetroArchExecutable():Promise<string>;

export function UploadSave(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UploadState(arg1:number,arg2:string,arg3:string):Promise<void>;

export function ValidateAssetPath(arg1:string,arg2:string):Promise<string>;
