// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {io} from '../models';

export function ClearImageCache():Promise<void>;

export function ConfigGetConfig():Promise<types.AppConfig>;

export function ConfigSave(arg1:types.AppConfig):Promise<void>;

export function DeleteRom(arg1:number):Promise<void>;

export function DeleteSave(arg1:number,arg2:string,arg3:string):Promise<void>;

export function DeleteState(arg1:number,arg2:string,arg3:string):Promise<void>;

export function DownloadFile(arg1:types.Game):Promise<io.ReadCloser>;

export function DownloadRom(arg1:number):Promise<string>;

export function DownloadRomToLibrary(arg1:number):Promise<void>;

export function DownloadServerSave(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function DownloadServerState(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function EventsEmit(arg1:string,arg2:Array<any>):Promise<void>;

export function GetCheevosCredentials():Promise<string|string>;

export function GetConfig():Promise<types.AppConfig>;

export function GetCoresForGame(arg1:number):Promise<Array<string>>;

export function GetCover(arg1:number,arg2:string):Promise<string>;

export function GetDefaultLibraryPath():Promise<string>;

export function GetLibrary(arg1:number,arg2:number,arg3:number):Promise<any>;

export function GetLibraryPath():Promise<string>;

export function GetPassword():Promise<string>;

export function GetPlatformCover(arg1:number,arg2:string):Promise<string>;

export function GetPlatforms():Promise<Array<types.Platform>>;

export function GetRetroArchPath():Promise<string>;

export function GetRom(arg1:number):Promise<types.Game>;

export function GetRomDir(arg1:types.Game):Promise<string>;

export function GetRomDownloadStatus(arg1:number):Promise<boolean>;

export function GetRomMHost():Promise<string>;

export function GetSaves(arg1:number):Promise<Array<types.FileItem>>;

export function GetServerSaves(arg1:number):Promise<Array<types.ServerSave>>;

export function GetServerStates(arg1:number):Promise<Array<types.ServerState>>;

export function GetStates(arg1:number):Promise<Array<types.FileItem>>;

export function GetUsername():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LogErrorf(arg1:string,arg2:Array<any>):Promise<void>;

export function LogInfof(arg1:string,arg2:Array<any>):Promise<void>;

export function Login():Promise<string>;

export function Logout():Promise<void>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:Array<string>):Promise<string>;

export function PlayRom(arg1:number):Promise<void>;

export function PlayRomWithCore(arg1:number,arg2:string):Promise<void>;

export function Quit():Promise<void>;

export function RomMDownloadSave(arg1:string):Promise<io.ReadCloser>;

export function RomMDownloadState(arg1:string):Promise<io.ReadCloser>;

export function RomMUploadSave(arg1:number,arg2:string,arg3:string,arg4:Array<number>):Promise<void>;

export function RomMUploadState(arg1:number,arg2:string,arg3:string,arg4:Array<number>):Promise<void>;

export function SaveConfig(arg1:types.AppConfig):Promise<string>;

export function SaveDefaultLibraryPath(arg1:string):Promise<void>;

export function SelectLibraryPath():Promise<string>;

export function SelectRetroArchExecutable():Promise<string>;

export function UploadSave(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UploadState(arg1:number,arg2:string,arg3:string):Promise<void>;

export function ValidateAssetPath(arg1:string,arg2:string):Promise<string>;

export function WindowHide():Promise<void>;

export function WindowSetAlwaysOnTop(arg1:boolean):Promise<void>;

export function WindowShow():Promise<void>;

export function WindowUnminimise():Promise<void>;
