// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function ClearImageCache() {
  return window['go']['main']['App']['ClearImageCache']();
}

export function CreateSaveSlot(arg1, arg2) {
  return window['go']['main']['App']['CreateSaveSlot'](arg1, arg2);
}

export function DeleteOrphanedRoms(arg1) {
  return window['go']['main']['App']['DeleteOrphanedRoms'](arg1);
}

export function DeleteRom(arg1) {
  return window['go']['main']['App']['DeleteRom'](arg1);
}

export function DeleteSave(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteSave'](arg1, arg2, arg3);
}

export function DeleteSaveSlot(arg1, arg2) {
  return window['go']['main']['App']['DeleteSaveSlot'](arg1, arg2);
}

export function DeleteServerSave(arg1) {
  return window['go']['main']['App']['DeleteServerSave'](arg1);
}

export function DeleteState(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteState'](arg1, arg2, arg3);
}

export function DownloadAndInstallRetroArch() {
  return window['go']['main']['App']['DownloadAndInstallRetroArch']();
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function DownloadFirmwareContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFirmwareContent'](arg1, arg2, arg3);
}

export function DownloadRomToLibrary(arg1) {
  return window['go']['main']['App']['DownloadRomToLibrary'](arg1);
}

export function DownloadServerSave(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DownloadServerSave'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadServerState(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DownloadServerState'](arg1, arg2, arg3, arg4, arg5);
}

export function EventsEmit(arg1, arg2) {
  return window['go']['main']['App']['EventsEmit'](arg1, arg2);
}

export function GetBiosDir() {
  return window['go']['main']['App']['GetBiosDir']();
}

export function GetCheevosCredentials() {
  return window['go']['main']['App']['GetCheevosCredentials']();
}

export function GetClientToken() {
  return window['go']['main']['App']['GetClientToken']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCoresForGame(arg1) {
  return window['go']['main']['App']['GetCoresForGame'](arg1);
}

export function GetCover(arg1, arg2) {
  return window['go']['main']['App']['GetCover'](arg1, arg2);
}

export function GetDefaultLibraryPath() {
  return window['go']['main']['App']['GetDefaultLibraryPath']();
}

export function GetFirmware(arg1) {
  return window['go']['main']['App']['GetFirmware'](arg1);
}

export function GetGameController(arg1) {
  return window['go']['main']['App']['GetGameController'](arg1);
}

export function GetGameSaveSlot(arg1) {
  return window['go']['main']['App']['GetGameSaveSlot'](arg1);
}

export function GetGameStartupFile(arg1) {
  return window['go']['main']['App']['GetGameStartupFile'](arg1);
}

export function GetLibrary(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetLibrary'](arg1, arg2, arg3, arg4);
}

export function GetLibraryPath() {
  return window['go']['main']['App']['GetLibraryPath']();
}

export function GetLocalGame(arg1) {
  return window['go']['main']['App']['GetLocalGame'](arg1);
}

export function GetPassword() {
  return window['go']['main']['App']['GetPassword']();
}

export function GetPlatform(arg1) {
  return window['go']['main']['App']['GetPlatform'](arg1);
}

export function GetPlatformCover(arg1, arg2) {
  return window['go']['main']['App']['GetPlatformCover'](arg1, arg2);
}

export function GetPlatforms(arg1, arg2) {
  return window['go']['main']['App']['GetPlatforms'](arg1, arg2);
}

export function GetResolvedPlatformSlug(arg1) {
  return window['go']['main']['App']['GetResolvedPlatformSlug'](arg1);
}

export function GetRetroArchPath() {
  return window['go']['main']['App']['GetRetroArchPath']();
}

export function GetRom(arg1) {
  return window['go']['main']['App']['GetRom'](arg1);
}

export function GetRomDir(arg1) {
  return window['go']['main']['App']['GetRomDir'](arg1);
}

export function GetRomDownloadStatus(arg1) {
  return window['go']['main']['App']['GetRomDownloadStatus'](arg1);
}

export function GetRomMHost() {
  return window['go']['main']['App']['GetRomMHost']();
}

export function GetRomStartupFiles(arg1) {
  return window['go']['main']['App']['GetRomStartupFiles'](arg1);
}

export function GetSaveSlots(arg1) {
  return window['go']['main']['App']['GetSaveSlots'](arg1);
}

export function GetSaves(arg1) {
  return window['go']['main']['App']['GetSaves'](arg1);
}

export function GetServerSaves(arg1) {
  return window['go']['main']['App']['GetServerSaves'](arg1);
}

export function GetServerSavesForSlot(arg1, arg2) {
  return window['go']['main']['App']['GetServerSavesForSlot'](arg1, arg2);
}

export function GetServerStates(arg1) {
  return window['go']['main']['App']['GetServerStates'](arg1);
}

export function GetStates(arg1) {
  return window['go']['main']['App']['GetStates'](arg1);
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function LogErrorf(arg1, arg2) {
  return window['go']['main']['App']['LogErrorf'](arg1, arg2);
}

export function LogInfof(arg1, arg2) {
  return window['go']['main']['App']['LogInfof'](arg1, arg2);
}

export function Login() {
  return window['go']['main']['App']['Login']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function OpenGameFolder(arg1) {
  return window['go']['main']['App']['OpenGameFolder'](arg1);
}

export function PlayRomWithCore(arg1, arg2) {
  return window['go']['main']['App']['PlayRomWithCore'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveLastUsedCore(arg1, arg2) {
  return window['go']['main']['App']['SaveLastUsedCore'](arg1, arg2);
}

export function ScanOrphanedRoms() {
  return window['go']['main']['App']['ScanOrphanedRoms']();
}

export function SelectLibraryPath() {
  return window['go']['main']['App']['SelectLibraryPath']();
}

export function SelectRetroArchExecutable() {
  return window['go']['main']['App']['SelectRetroArchExecutable']();
}

export function SetGameController(arg1, arg2) {
  return window['go']['main']['App']['SetGameController'](arg1, arg2);
}

export function SetGameSaveSlot(arg1, arg2) {
  return window['go']['main']['App']['SetGameSaveSlot'](arg1, arg2);
}

export function SetGameStartupFile(arg1, arg2) {
  return window['go']['main']['App']['SetGameStartupFile'](arg1, arg2);
}

export function SetPlatformFirmware(arg1, arg2) {
  return window['go']['main']['App']['SetPlatformFirmware'](arg1, arg2);
}

export function SyncOfflineMetadata() {
  return window['go']['main']['App']['SyncOfflineMetadata']();
}

export function ToggleDisableMetadata() {
  return window['go']['main']['App']['ToggleDisableMetadata']();
}

export function ToggleOfflineMode() {
  return window['go']['main']['App']['ToggleOfflineMode']();
}

export function ToggleUsePlatformFolder() {
  return window['go']['main']['App']['ToggleUsePlatformFolder']();
}

export function UpdateRetroArchBios() {
  return window['go']['main']['App']['UpdateRetroArchBios']();
}

export function UpdateRetroArchCores() {
  return window['go']['main']['App']['UpdateRetroArchCores']();
}

export function UploadSave(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadSave'](arg1, arg2, arg3);
}

export function UploadSaveToSlot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadSaveToSlot'](arg1, arg2, arg3, arg4);
}

export function UploadState(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadState'](arg1, arg2, arg3);
}

export function ValidateAssetPath(arg1, arg2) {
  return window['go']['main']['App']['ValidateAssetPath'](arg1, arg2);
}

export function WindowHide() {
  return window['go']['main']['App']['WindowHide']();
}

export function WindowSetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['WindowSetAlwaysOnTop'](arg1);
}

export function WindowShow() {
  return window['go']['main']['App']['WindowShow']();
}

export function WindowUnminimise() {
  return window['go']['main']['App']['WindowUnminimise']();
}
