// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigGetConfig() {
  return window['go']['main']['App']['ConfigGetConfig']();
}

export function ConfigSave(arg1) {
  return window['go']['main']['App']['ConfigSave'](arg1);
}

export function DeleteRom(arg1) {
  return window['go']['main']['App']['DeleteRom'](arg1);
}

export function DeleteSave(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteSave'](arg1, arg2, arg3);
}

export function DeleteState(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteState'](arg1, arg2, arg3);
}

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function DownloadRom(arg1) {
  return window['go']['main']['App']['DownloadRom'](arg1);
}

export function DownloadRomToLibrary(arg1) {
  return window['go']['main']['App']['DownloadRomToLibrary'](arg1);
}

export function DownloadServerSave(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DownloadServerSave'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadServerState(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DownloadServerState'](arg1, arg2, arg3, arg4, arg5);
}

export function EventsEmit(arg1, arg2) {
  return window['go']['main']['App']['EventsEmit'](arg1, arg2);
}

export function GetCheevosCredentials() {
  return window['go']['main']['App']['GetCheevosCredentials']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCover(arg1, arg2) {
  return window['go']['main']['App']['GetCover'](arg1, arg2);
}

export function GetLibrary() {
  return window['go']['main']['App']['GetLibrary']();
}

export function GetLibraryPath() {
  return window['go']['main']['App']['GetLibraryPath']();
}

export function GetPassword() {
  return window['go']['main']['App']['GetPassword']();
}

export function GetPlatformCover(arg1, arg2) {
  return window['go']['main']['App']['GetPlatformCover'](arg1, arg2);
}

export function GetPlatforms() {
  return window['go']['main']['App']['GetPlatforms']();
}

export function GetRetroArchPath() {
  return window['go']['main']['App']['GetRetroArchPath']();
}

export function GetRom(arg1) {
  return window['go']['main']['App']['GetRom'](arg1);
}

export function GetRomDir(arg1) {
  return window['go']['main']['App']['GetRomDir'](arg1);
}

export function GetRomDownloadStatus(arg1) {
  return window['go']['main']['App']['GetRomDownloadStatus'](arg1);
}

export function GetRomMHost() {
  return window['go']['main']['App']['GetRomMHost']();
}

export function GetSaves(arg1) {
  return window['go']['main']['App']['GetSaves'](arg1);
}

export function GetServerSaves(arg1) {
  return window['go']['main']['App']['GetServerSaves'](arg1);
}

export function GetServerStates(arg1) {
  return window['go']['main']['App']['GetServerStates'](arg1);
}

export function GetStates(arg1) {
  return window['go']['main']['App']['GetStates'](arg1);
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LogErrorf(arg1, arg2) {
  return window['go']['main']['App']['LogErrorf'](arg1, arg2);
}

export function LogInfof(arg1, arg2) {
  return window['go']['main']['App']['LogInfof'](arg1, arg2);
}

export function Login() {
  return window['go']['main']['App']['Login']();
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function PlayRom(arg1) {
  return window['go']['main']['App']['PlayRom'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RomMDownloadSave(arg1) {
  return window['go']['main']['App']['RomMDownloadSave'](arg1);
}

export function RomMDownloadState(arg1) {
  return window['go']['main']['App']['RomMDownloadState'](arg1);
}

export function RomMUploadSave(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RomMUploadSave'](arg1, arg2, arg3, arg4);
}

export function RomMUploadState(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RomMUploadState'](arg1, arg2, arg3, arg4);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveDefaultLibraryPath(arg1) {
  return window['go']['main']['App']['SaveDefaultLibraryPath'](arg1);
}

export function SelectLibraryPath() {
  return window['go']['main']['App']['SelectLibraryPath']();
}

export function SelectRetroArchExecutable() {
  return window['go']['main']['App']['SelectRetroArchExecutable']();
}

export function UploadSave(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadSave'](arg1, arg2, arg3);
}

export function UploadState(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadState'](arg1, arg2, arg3);
}

export function ValidateAssetPath(arg1, arg2) {
  return window['go']['main']['App']['ValidateAssetPath'](arg1, arg2);
}

export function WindowHide() {
  return window['go']['main']['App']['WindowHide']();
}

export function WindowSetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['WindowSetAlwaysOnTop'](arg1);
}

export function WindowShow() {
  return window['go']['main']['App']['WindowShow']();
}

export function WindowUnminimise() {
  return window['go']['main']['App']['WindowUnminimise']();
}
