// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRom(arg1) {
  return window['go']['main']['App']['DeleteRom'](arg1);
}

export function DeleteSave(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteSave'](arg1, arg2, arg3);
}

export function DeleteState(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteState'](arg1, arg2, arg3);
}

export function DownloadRom(arg1) {
  return window['go']['main']['App']['DownloadRom'](arg1);
}

export function DownloadRomToLibrary(arg1) {
  return window['go']['main']['App']['DownloadRomToLibrary'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCover(arg1, arg2) {
  return window['go']['main']['App']['GetCover'](arg1, arg2);
}

export function GetLibrary() {
  return window['go']['main']['App']['GetLibrary']();
}

export function GetPlatformCover(arg1, arg2) {
  return window['go']['main']['App']['GetPlatformCover'](arg1, arg2);
}

export function GetPlatforms() {
  return window['go']['main']['App']['GetPlatforms']();
}

export function GetRom(arg1) {
  return window['go']['main']['App']['GetRom'](arg1);
}

export function GetRomDownloadStatus(arg1) {
  return window['go']['main']['App']['GetRomDownloadStatus'](arg1);
}

export function GetSaves(arg1) {
  return window['go']['main']['App']['GetSaves'](arg1);
}

export function GetStates(arg1) {
  return window['go']['main']['App']['GetStates'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login() {
  return window['go']['main']['App']['Login']();
}

export function PlayRom(arg1) {
  return window['go']['main']['App']['PlayRom'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectLibraryPath() {
  return window['go']['main']['App']['SelectLibraryPath']();
}

export function SelectRetroArchExecutable() {
  return window['go']['main']['App']['SelectRetroArchExecutable']();
}

export function UploadSave(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadSave'](arg1, arg2, arg3);
}

export function UploadState(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadState'](arg1, arg2, arg3);
}
